### ISSUE TITLE
Pa11y to test internal sites that are not on the internet but on intranet.

### ISSUE THREAD

**Issue by qaDream77** [nature/pa11y-webservice#8]
I installed the pa11y command line tool and am able to test any live site, I am wondering how I would go about testing development sites which can't be accessed outside of the network.

Error: PhantomJS failed to open "https://dev.test.cf.mytestsite.ca/foobar.html"
Error: Page "https://dev.test.cf.mytestsite.ca/foobar.html" could not be loaded
    at /usr/local/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:67:17
    at Proto.apply (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
    at D.dnode.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:128:22)
    at SockJSConnection.ondata (stream.js:51:26)
    at SockJSConnection.emit (events.js:107:17)
    at Session.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/transport.js:220:25)
    at WebSocketReceiver.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:102:40)
    at /usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:75:22

Is there any way to install, pa11y as well as it's requirements onto a local server and run everything in house without any calls to outside?

Thank you for the help!

**Comment by rowanmanning** [comment]
See https://github.com/nature/pa11y/issues/90, closing this in favour of that issue.
